//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPICrudDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryInfo
    {
        public int SalarySheetNo { get; set; }
        public int EmpCode { get; set; }
        public Nullable<System.DateTime> DateOfSalary { get; set; }
        public decimal Basic { get; set; }
        public Nullable<decimal> Hra { get; set; }
        public Nullable<decimal> Da { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
    
        public virtual EmpProfile EmpProfile { get; set; }
    }
}
